### ISSUE TITLE
Silence decorators @ related warnings

### ISSUE THREAD

**Issue by karellm** [ember-cli/ember-cli-eslint#148]
I have a new Ember project and I'm experimenting with decorators. I tried many different things to silence the eslint warnings about the `@` in the code without success. Could you point me in the right direction? Thanks!

**Comment by Turbo87** [comment]
see https://github.com/eslint/eslint/issues/4096

**Comment by karellm** [comment]
@Turbo87 I have seen this of course (it didn't work). But I've also read #81 which talks about removing the `babel-eslint` parser because the default one supports ES6/7 features now.

In case I'm missing something from the link you shared, I would greatly appreciate a slightly more precise pointer. Thanks!

**Comment by Turbo87** [comment]
@karellm decorators are not ES6/7 yet. they are still an experimental part of JS, which is not yet standardized.

`ember-cli-eslint` had used `babel-eslint` in the past, so in theory it should still work. feel free to provide more details on *what* didn't work, and try to come up with a reproduction so that we can try to fix any related issues.

**Comment by karellm** [comment]
I confirm that adding `parser: 'babel-eslint'` to the `.eslintrc.js` generated file worked at silencing the warnings. I might have done something wrong when I first tried it. Thanks for the support!

**Comment by Turbo87** [comment]
@karellm thanks for the feedback
