### ISSUE TITLE
Ember serve fails because of test-generation

### ISSUE THREAD

**Issue by ismay** [ember-cli/ember-cli-eslint#18]
The method for generating tests outlined in the readme doesn't work with `ember serve` because it isn't environment specific. Thus, it tries to generate tests and import `qunit` when you try to access `localhost:4200`:

```
Error: Could not find module `qunit` imported from `my-project/tests/factories/item.eslint-test`
```

Which doesn't work because as far as I know, qunit is only available in the testing environment. I'd say test generation should be exclusive to the testing environment. I'm unsure what the best approach would be though.

**Comment by jonathanKingston** [comment]
Does adding a `.eslintrc` file into the tests dir fix this?

**Comment by ismay** [comment]
I have an `.eslintrc` file in my tests dir. That doesn't seem to fix it. Which makes sense, since the tests are being generated in the Brocfile.js, without discriminating between environments (i.e. `production`, `testing`, etc.).

I don't know if you're using it already, but the ember-cli [postprocessTree](http://hashrocket.com/blog/posts/a-compendium-of-hooks-in-embercli#postprocess) hook should be the way to trigger environment specific linting, as far as I know.

**Comment by jonathanKingston** [comment]
@ismay I actually use `lintTree` hook which is the dedicated hook for linting, they actually settled for that after: https://github.com/ef4/ember-cli-mocha/commit/2210851ee3c365ca4dc34bf812d378f37c12a307

I suspect something might have changed in qunit since this was implemented. (I don't actually use qunit myself so it gets less testing).

What I think might need to happen is testing for qunit in your test generator rather than importing it.

Like I say this was verified as working at the time so something must have changed.

Long term when closer integration of linting to ember-cli happens, generators should go away :).

**Comment by ismay** [comment]
> I actually use lintTree hook which is the dedicated hook for linting

Ah, that's even better. So then that shouldn't be the problem. I'll see if I can fix it by testing for qunit. Also, what testing suite are you using? I thought using other testing suites with ember-cli wasn't really possible.
