### ISSUE TITLE
Remove dependency on circular-json@0.3.3

### ISSUE THREAD

**Issue by jacopolanzoni** [ember-cli/ember-cli-eslint#306]
The package `ember-cli-eslint` has now a deprecated dependency on
```
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
```
The dependency tree is the followin:
```
└─┬ ember-cli-eslint@5.0.0
  └─┬ broccoli-lint-eslint@5.0.0
    └─┬ eslint@5.9.0
      └─┬ file-entry-cache@2.0.0
        └─┬ flat-cache@1.3.4
          └── circular-json@0.3.3
```
Can you please update `broccoli-lint-eslint`?

**Comment by Turbo87** [comment]
as you can see in the tree `circular-json` is a subdependency of `eslint`. as we don't maintain `eslint` itself there is not much we can do other than waiting for a new release which fixes this issue.

**Comment by Turbo87** [comment]
> Should not you keep this open until that is fixed?

there is quite a maintenance cost attached to keeping track of downstream issues like this. eventually https://github.com/eslint/eslint/issues/11052 will get fixed at which point our package will also be fixed automatically without us having to do anything. since there is no action required on our side I don't think keeping an issue around is needed.
