### ISSUE TITLE
Adding .eslintrc to tests dir leads to confusing results

### ISSUE THREAD

**Issue by danny-andrews** [ember-cli/ember-cli-eslint#59]
Because of the way rules [cascade](http://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy) in eslint, the .eslintrc file in the tests dir will completely overrule the rules in the .eslintrc file at the project root. This leads to very confusing results when linting you project. I would recommend not creating the .eslintrc file in the tests directory and let people deal with uses of `console` in their tests themselves.

**Comment by BrianSipple** [comment]
I agree that a full override is apt to be a bit extreme — thank you for raising this issue, @danny-andrews.
 
There's a significant refactoring of the way we handle base rules & configs underway in #53, which seems like it's ready to be merged. This removes the `console` rule from the test config and instead just sets the [`embertest` environment](http://eslint.org/docs/user-guide/configuring#specifying-environments). 

That said, @jonathanKingston, @Turbo87, @mmun, & @alexlafroscia, what are your thoughts on having `tests/.eslintrc` extend the root config by default? I've actually been taking this approach in my own projects, and it seems like that may well be a reasonable starting point for most users.

**Comment by Turbo87** [comment]
I don't understand the problem here. The cascading in ESLint is exactly the reason why it's a good thing to have the `tests/.eslintrc` file.

> what are your thoughts on having tests/.eslintrc extend the root config by default?

that functionality is already built into ESLint unless I totally misunderstood http://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy

**Comment by BrianSipple** [comment]
I think the _potential_ issue is that if I had a custom configuration for the root of my project, nothing there will apply inside of the `/test` directory since eslint will detect the config in `/test` -- and it's not extending from the root with something like `extends: ../.eslintrc`. 

That said, this could be seen as an advantage -- `test/` has it's own scope by default, and saying `extends: ../.eslintrc` would be a fairly trivial step for anyone who didn't want to have the separation.

**Comment by mmun** [comment]
I agree with @Turbo87.

@BrianSipple Adding `extends: ../.eslintrc` without also adding `root: true` is misleading (since removing it does nothing). I don't think the extra verbosity makes things any clearer. You still end up needing to know what `root` means and hence how the rule cascade works.

**Comment by Turbo87** [comment]
> I think the potential issue is that if I had a custom configuration for the root of my project, nothing there will apply inside of the /test directory

why do you think that? the way I read that link above is that the custom config from the root file *will* apply in the test directory too unless specifically overwritten there.

**Comment by BrianSipple** [comment]
@Turbo87 Ah, you're right. I've always been explicitly extending, and so I guess I never realized that. 

With that in mind, then, I think this issue is closable. (One takeaway: it would be great if we could resolve #53 soon as well 😄 ).
