### ISSUE TITLE
Support StandardJS

### ISSUE THREAD

**Issue by lolmaus** [ember-cli/ember-cli-eslint#95]
http://standardjs.com/ is becoming a big thing and it would be great if using it in Ember was straightforward.

I tried installing [eslint-config-standard](https://github.com/feross/eslint-config-standard) and updating `.jshintrc` to have `"extends": "standard"`.

It works, but it crashes due to this issue: https://github.com/babel/babel-eslint/issues/316.

> TypeError: Cannot read property 'value' of undefined
>     at getStarToken (/home/lolmaus/Code/launchpad2/node_modules/ember-cli-eslint/node_modules/broccoli-lint-eslint/node_modules/eslint/lib/rules/generator-star-spacing.js:68:25)

It's using `eslint/lib/rules/generator-star-spacing.js` but StandardJS needs `eslint-plugin-babel/rules/generator-star-spacing.js`.

I wasn't able to figure out how to tell `ember-cli-eslint` to use that.

**Comment by alexlafroscia** [comment]
Can you paste your ESLint config here or link a Gist to it?

**Comment by alexlafroscia** [comment]
Actually, on second thought, this doesn't seem like an issue with `ember-cli-eslint` but instead one with `eslint-config-standard`.

You mentioned that it's picking up the wrong rule, using `generator-star-spacing` instead of `babel/generator-star-spacing`.  It's likely due to [this line in their configuration](https://github.com/feross/eslint-config-standard/blob/730e8eb58f724351ca088e01abac6a7cfdae0ec9/eslintrc.json#L41) where they specifically enable the ESLint-provided version if the rule.

If you want a "quick fix" then you can probably do something like this in your configuration (although I have no actually run this to verify, I'm just going based on how ESLint config files are composed):

```json
(
  "extends": "standard",
  "rules": {
    "generator-star-spacing": "off",
    "babel/generator-star-spacing": "error"
  }
}
```

Or, if you feel that should be the default behavior for that plugin, you could always make a pull request back to `eslint-config-standard` with the same change.

**Comment by lolmaus** [comment]
That does the trick!

Thank you so much @alexlafroscia, I owe you a pint. :bow:

**Comment by alexlafroscia** [comment]
Happy to help!
