### ISSUE TITLE
Upgrade to ESLint 3

### ISSUE THREAD

**Issue by alexlafroscia** [ember-cli/ember-cli-eslint#97]
Piggybacking off of [ember-cli/broccoli-lint-eslint#40](https://github.com/ember-cli/broccoli-lint-eslint/issues/40), it would be really nice to support ESLint 3 in this package as well.  I know that having a "main" ESLint 3 branch and "legacy" 2.X branch would be a lot of work for the maintainers here, but I'm sure there are a lot of people that would like to upgrade to the latest version and aren't stuck with an unsupported Node version.

There is a PR open for this already at #96 but accepting it means keeping two branches up-to-date, just like `broccoli-lint-eslint` is planning to do.  Should we do that here, too?

**Comment by alexlafroscia** [comment]
Great point, totally agree.  I really wish we could just drop ESLint 2 support altogether 😒 But, the reasons listed on the related `broccoli-lint-eslint` seem valid, regarding supporting Node 0.12 (for now).

**Comment by alexlafroscia** [comment]
Although, at the same time, I don't think it's unfair to tell people to install an old version of `ember-cli-eslint` if they need Node 0.12 support.

**Comment by Turbo87** [comment]
> I don't think it's unfair to tell people to install an old version of ember-cli-eslint if they need Node 0.12 support.

I totally agree, but someone has to maintain it then...

**Comment by alexlafroscia** [comment]
Do they, though? What's wrong with just not updating both?  If they need Node 0.12 support they just don't get new features.

**Comment by BrianSipple** [comment]
> Do they, though? What's wrong with just not updating both? If they need Node 0.12 support they just don't get new features.

Hmm... that's a salient point. But -- and I think this is what @Turbo87 was getting at -- I think we're still at a phase where there's a strong possibility of discovering more bugs in the current version (not to mention [those we might have already discovered](https://github.com/ember-cli/ember-cli-eslint/issues)) that will be nice to patch up for _everyone_. If all we had to consider was "new features", I'd say let's go for it... but I don't know if we're quite there yet.

**Comment by jcano** [comment]
As I see it, this is a matter of choosing who to favor. As it stands now, users are forced to use a ESlint version lower than 3, which  doesn't affect 0.10 users but it's holding back users who are up-to-date with their development environment.To be clear, this is not only affecting update freaks like me, but also new users coming Ember with the latest versions of Node and ESlint.

In my opinion, and I'm probably wrong as I don't know this community that well, the best way to handle this would be to issue a deprecation warning for people to upgrade to 0.12 (which is not that far from 0.10 and it's still very old) and stop fixing bugs for that environment. Many of those bugs will actually either change or be fixed with ESlint3 in any case. If any 0.10 users want to keep the support for their version, they are always welcome to maintain it.

It's a tough call, but deciding not to support ESlint3 means holding people back and making it a bit harder for new people to get into Ember using ESlint.

**Comment by Turbo87** [comment]
@jcano I think the minimum node version for eslint 3 is 4.0, not 0.12

**Comment by jcano** [comment]
@Turbo87 I just checked, and yes, it's 4.0. Then the decision is more difficult. I got confused with the reference to 0.12, I really thought that was the minimum version.

**Comment by rtablada** [comment]
I would refresh this discussion. Many popular eslint configs such as the airbnb config WILL not work with eslint 2.x since the indentation rule changed formatting from 2.0 to 3.0

**Comment by BrianSipple** [comment]
I think there might be a really good opportunity to pursue this now with #107 causing us to bump the major version. We can make ESLint 3.x support a part of the next version as well, cut off a separate 2.x branch, clearly document the difference, and, as a bonus,  have parity with [the way `broccoli-lint-eslint` is handling the same situation](https://github.com/ember-cli/broccoli-lint-eslint/pull/55#issuecomment-240933566).

**Comment by aaroncraigongithub** [comment]
Is there any way to turn off linting during the build phase while this is being sorted out?  I'm loathe to have my brand new ember app forced to pin an old version of the airbnb config until this gets sorted out, and since I can run the linter on my own, I don't see any reason to be forced to use the built in linter during the build.

**Comment by crhayes** [comment]
What specifically needs to happen to get this shipped and a new version tagged with ESLint 3.x support? Is there anything we can do to help?

**Comment by Turbo87** [comment]
@crhayes not much actually and due to the increased number of requests I think we might be convinced by now that we should do it.

@BrianSipple we should probably try to keep the diffs between the branches small. continue working on the 2.x branch for now and merge the changes up into the 3.x branch.

**Comment by crhayes** [comment]
@Turbo87 Sounds great. I have a bunch of rules I'd love to add once this is all complete. If there's anything I can do let me know and I'll try my best :)

**Comment by Turbo87** [comment]
@crhayes this repository now has a `3.x` branch and we will soon release a v3.0.0 from that. feel free to test this and give feedback!

**Comment by michalsnik** [comment]
Great to hear it @Turbo87 ! Can't wait for the official support.

I'd like to update https://github.com/netguru/eslint-plugin-netguru-ember to use newest eslint and airbnb-config so this release is something I'm waiting for a while :)

**Comment by crhayes** [comment]
@Turbo87 Thanks for the update, will test and let you know if I have any issues :)

**Comment by Turbo87** [comment]
https://github.com/ember-cli/ember-cli-eslint/releases/tag/v3.0.0

**Comment by crhayes** [comment]
@Turbo87 thanks! It's going to be so hard to commit code to my code base after I enable all the new rules I've been looking at 😆
